version: "3.8"
services:
  web:
    build: .
    ports: ["8080:8080"]
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - REDIS_URL=redis://redis:6379/0
    depends_on: [redis]
  worker:
    build: .
    command: rq worker --url redis://redis:6379/0
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - REDIS_URL=redis://redis:6379/0
    depends_on: [redis]
  redis:
    image: redis:7-alpine